[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bote"
version = "2.0.0"
description = "Send email messages and enforce encryption."
authors = ["Rüdiger Voigt <projects@ruediger-voigt.eu>"]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://github.com/RuedigerVoigt/bote"
repository = "https://github.com/RuedigerVoigt/bote"
documentation = "https://github.com/RuedigerVoigt/bote"
keywords = ["email", "smtp", "encryption", "security"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS :: MacOS X",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Topic :: System :: Monitoring",
    "Topic :: Communications :: Email",
    "Topic :: Security :: Cryptography",
]
packages = [{include = "bote"}]
include = ["bote/py.typed"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/RuedigerVoigt/bote/issues"
"Changelog" = "https://github.com/RuedigerVoigt/bote/blob/master/CHANGELOG.md"
"Source Code" = "https://github.com/RuedigerVoigt/bote"

[tool.poetry.dependencies]
python = "^3.10"
compatibility = ">=2.0.0"
userprovided = ">=2.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0.0"
pytest-mock = "^3.0.0"
pytest-cov = "^7.0.0"
pyfakefs = "^5.0.0"
mypy = "^1.0.0"
flake8 = "^7.0.0"
pylint = "^4.0.0"
coverage = "^7.0.0"
